title: 岛本和彦漫画资源站
email: wemapls@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Powered by jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  LChuo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
encoding: utf-8
